PACKAGE_NAME="kernel-proc-lab"
PACKAGE_VERSION="0.8.0"
BUILT_MODULE_NAME[0]="kernel_proc_lab"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
MAKE[0]="make KDIR=/lib/modules/${kernelver}/build kernel_proc_lab.ko"
CLEAN="make clean"
